### ISSUE TITLE
Update to support Nornir 3

### ISSUE THREAD

**Issue by kn-winter** [carlmontanari/nornsible#4]
Hi Carl,

Nornsible is great and provides just what I'm looking for.  Do you have any plan to update it to run with Nornir 3?

Thanks,
Khiem

**Comment by carlmontanari** [comment]
Hey @kn-winter !

I don't use nornir for anything anymore so its already more effort than I want to be maintaining nornir-scrapli hah! So, no, I do not have any plans, however I'd be happy to review and merge PRs/make a release if somebody wants to do so!

Carl

**Comment by carlmontanari** [comment]
Guess I'll close this for now. Like I said, happy to review/merge some stuff though if anyone is keen to add things!
